apiVersion: v1
kind: Secret
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:shion13/argocd-app-of-apps.git
  sshPrivateKey: |
    ${argocd_private_key}
