apiVersion: v1
kind: Secret
metadata:
  name: helm-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:shion13/helm-charts.git
  sshPrivateKey: |
    ${helm_chart_private_key}
