{{- range $key, $val := .Values.argocdApplications -}}
{{ if not .disable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: app-of-apps
spec:
  project: {{ $.Values.global.spec.project }}
  sources:
    - repoURL: {{ .repoURL }}
      chart: {{ $key }}
      targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
      path: charts/{{ $key }}
      helm:
        valueFiles:
        - $values/values/{{ $key }}-values.yaml
    - repoURL: git@github.com:shion13/argocd-app-of-apps.git
      targetRevision: HEAD
      ref: values
  destination:
    namespace: {{ default $.Values.global.spec.destination.namespace  .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if not .disableAutomated }}
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - PruneLast=true 
      - CreateNamespace=true
---
{{- end }}
{{- end }}
